import packageJson from "../../package.json" with { type: "json" };
import { isSea } from "node:sea";

const DEFAULT_PORT = 9229;

const APP_VERSION = String(packageJson.version ?? "0.0.0");

const APP_DISPLAY_VERSION = isSea() ? APP_VERSION : `${APP_VERSION}.dev`;

const TARGET_POLL_MS = 1_500;

const QUOTA_REFRESH_MS = 60_000;

const MODEL_CATALOG_REFRESH_MS = 4 * 60_000 + 30_000;

const MODEL_CATALOG_BUSY_RETRY_MS = 30_000;

const DEEPSEEK_BALANCE_REFRESH_MS = 5 * 60_000;

const STARTUP_GRACE_MS = 30_000;

const TOKEN_USAGE_FALLBACK_MS = 15_000;

const WIDGET_HEALTH_CHECK_MS = 15_000;

const TOKEN_USAGE_STABILITY_GRACE_MS = 5_000;

const INJECTION_ERROR_LOG_INTERVAL_MS = 10_000;

const DEBUG_LOGGING = process.env.CODEX_QUOTA_DEBUG === "1";

export { DEFAULT_PORT, APP_DISPLAY_VERSION, TARGET_POLL_MS, QUOTA_REFRESH_MS, MODEL_CATALOG_REFRESH_MS, MODEL_CATALOG_BUSY_RETRY_MS, DEEPSEEK_BALANCE_REFRESH_MS, STARTUP_GRACE_MS, TOKEN_USAGE_FALLBACK_MS, INJECTION_ERROR_LOG_INTERVAL_MS, DEBUG_LOGGING, WIDGET_HEALTH_CHECK_MS, TOKEN_USAGE_STABILITY_GRACE_MS };
